/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-05-30 00:18:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1464141290293L));
    _jspx_dependants.put("jar:file:/C:/pleiades/workspace/hotel-site/hotel_site/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HOTEL_IZUMI/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1329370132000L));
    _jspx_dependants.put("/WEB-INF/views/../css/style.css", Long.valueOf(1464223301311L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1464141289923L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar", Long.valueOf(1464141290023L));
    _jspx_dependants.put("jar:file:/C:/pleiades/workspace/hotel-site/hotel_site/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HOTEL_IZUMI/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fname_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fid.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fname_005fid.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

boolean cnt=false;
int id=0;
String Wdate=null;
String Wroom=null;
String year=null;
String month=null;
String dateA=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=Shift_JIS\">\r\n");
      out.write("    <style type=\"text/css\">");
      out.write("html{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    margin-top:-20px;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("}\r\n");
      out.write(".top{\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tmargin-left:auto;\r\n");
      out.write("\tmargin-right:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("    top : 0px;\r\n");
      out.write("    padding : 10px;\r\n");
      out.write("    margin : 10px;\r\n");
      out.write("    text-align : center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents img{\r\n");
      out.write("    padding-bottom:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents button {\r\n");
      out.write("    font-size: 1.4em;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    padding: 10px 30px;\r\n");
      out.write("    background-color: #200;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    border-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table{\r\n");
      out.write("    border:0;\r\n");
      out.write("    background-color:#CCCCCC;\r\n");
      out.write("    font-size:24px;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("    width:200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table3{\r\n");
      out.write("    border:0;\r\n");
      out.write("    background-color:#CCCCCC;\r\n");
      out.write("    font-size:24px;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("    width:200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*--------calender----------*/\r\n");
      out.write("#Sunday{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    width:200;\r\n");
      out.write("    height:40;\r\n");
      out.write("    background-color:#C7D8ED;\r\n");
      out.write("    color:#FF3300;\r\n");
      out.write("    padding:15px;\r\n");
      out.write("}\r\n");
      out.write("#MonFri{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    width:200;\r\n");
      out.write("    background-color:#C7D8ED;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("    padding:15px;\r\n");
      out.write("}\r\n");
      out.write("#Saturday{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    width:200;\r\n");
      out.write("    background-color:#C7D8ED;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("    padding:15px;\r\n");
      out.write("}\r\n");
      out.write("#Saturday2{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    width:200;\r\n");
      out.write("    background-color:#A6C0E1;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("}\r\n");
      out.write("#Sunday2{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    height:40;\r\n");
      out.write("    background-color:#FFCC99;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("}\r\n");
      out.write("#Weekday{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    background-color:#FFFFFF;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("    width:200;\r\n");
      out.write("}\r\n");
      out.write("#publicholiday{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    background-color:#FF3300;\r\n");
      out.write("    color:#FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("#table2 tr td{\r\n");
      out.write("    border:0;\r\n");
      out.write("    font-size:24px;\r\n");
      out.write("    color:#666666;\r\n");
      out.write("    width:400px;\r\n");
      out.write("}\r\n");
      out.write("#float{\r\n");
      out.write("    float:left;\r\n");
      out.write("}\r\n");
      out.write("/* --------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    height: 75px;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    text-align : center;\r\n");
      out.write("    background-color : #3A0101;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#header h1{\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    font-family: 'Times New Roman', Times, serif;\r\n");
      out.write(" \tcolor:#ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#top{\r\n");
      out.write("    font-size: 200%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#oneset{\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("\r\n");
      out.write("\tborder-width: thick;\r\n");
      out.write("\tborder-color: #999AAA;\r\n");
      out.write("\tborder-style: ridge;\r\n");
      out.write("}\r\n");
      out.write("#name\r\n");
      out.write("{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("\tfont-size: 150%;\r\n");
      out.write("    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    background-color: #999AAA;\r\n");
      out.write("    font-family: 'Times New Roman', Times, serif;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#message{\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("    padding-left: 300px;\r\n");
      out.write("\tfont-size: 150%;\r\n");
      out.write("\r\n");
      out.write("\ttext-align: left; margin-left: 100px; margin-right: 0px; width: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*---------üÍtH[----------*/\r\n");
      out.write("\r\n");
      out.write("#reservation{\r\n");
      out.write("\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    margin-bottom:50px;\r\n");
      out.write("    font-family: 'Times New Roman', Times, serif;\r\n");
      out.write(" \tcolor:#000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#form{\r\n");
      out.write("    margin-top:30px\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.button2 {\r\n");
      out.write("    font-size: 1.4em;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    padding: 30px 20px;\r\n");
      out.write("    background-color: #3A0101;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    border-style: none;\r\n");
      out.write("    font-family: 'Times New Roman', Times, serif;\r\n");
      out.write("    box-shadow:4px 4px #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("footer ------------------------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("    margin-top:30px;\r\n");
      out.write("    border-top:2px solid #3A1010;\r\n");
      out.write("    padding-top:20px;\r\n");
      out.write("    padding-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer p{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("}\r\n");
      out.write("#footer p a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("#footborder hr{\r\n");
      out.write("    border-color:#3A1010;\r\n");
      out.write("    border-width:1px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("      input.button2{\r\n");
      out.write("        font-size: 1.4em;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        padding: 30px 20px;\r\n");
      out.write("        background-color: #3A0101;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        border-style: none;\r\n");
      out.write("        font-family: 'Times New Roman', Times, serif;\r\n");
      out.write("        box-shadow:4px 4px #555;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    <title>お客様情報の入力</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("      <div id=\"header h1\"><h1><a HREF=\"http://localhost:8080/Izumi/top\" STYLE=\"text-decoration:none\"><font color=\"#FFFFFF\">HOTEL&nbsp;&nbsp;&nbsp;IZUMI</font></a></h1></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fid.get(org.springframework.web.servlet.tags.form.FormTag.class);
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/views/form.jsp(40,4) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setModelAttribute("formModel");
      // /WEB-INF/views/form.jsp(40,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("form");
      // /WEB-INF/views/form.jsp(40,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setId("form");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      <input type=\"hidden\" name=\"mcode\" value=\"UTF-8\">\r\n");
            out.write("\r\n");
            out.write("      ");

      Connection con = null;
      Statement stmt = null;
      ResultSet rs = null;
      try {
        con = DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","e78jOn6L");
        stmt = con.createStatement();
        rs =stmt.executeQuery("select * from hotel.tbroom");
        while(rs.next()) {
          id=rs.getInt(1);
          Integer ida =new Integer(id);
          String idb =ida.toString();
          String date =rs.getString(2);
          String room =rs.getString(3);
          Wdate=date;
          Wroom=room;
        }
      }
      catch (Exception e) {
        System.out.println("データベース接続エラー"+ e);
      }

      year=Wdate.substring(0,2);
      year="20"+year+"年";
      month=Wdate.substring(2,4);
      month=month+"月";
      dateA=Wdate.substring(4,6);
      dateA=dateA+"日";
      
            out.write("\r\n");
            out.write("\r\n");
            out.write("      <p ID=reservation>");
 out.println(year+month+dateA);
            out.write("</p>\r\n");
            out.write("\r\n");
            out.write("      <p>以下のフォームにご入力の上、「入力内容の確認画面へ」ボタンをクリックしてください。</p>\r\n");
            out.write("      <p><font color=\"#ff0000\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</font></p>\r\n");
            out.write("\r\n");
            out.write("    <table>\r\n");
            out.write("       <tr>\r\n");
            out.write("         <th><label>ご利用人数</label></th>\r\n");
            out.write("         <td></td>\r\n");
            out.write("         <td>");
            if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write(" <span class=\"supplement\" >名様</span><br>\r\n");
            out.write("         </td>\r\n");
            out.write("       </tr>\r\n");
            out.write("\r\n");
            out.write("       <tr>\r\n");
            out.write("         <th><label for=\"name1\">ご依頼者名</label></th>\r\n");
            out.write("         <td></td>\r\n");
            out.write("         <td>");
            if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("<br>\r\n");
            out.write("         <span class=\"supplement\">例） 田具 太郎</span></td>\r\n");
            out.write("       </tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<th><label for=\"name2\">ご依頼者名 <span class=\"supplement\">（フリガナ）</span></label></th>\r\n");
            out.write("<td></td>\r\n");
            out.write("<td>");
            if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("<br>\r\n");
            out.write("<span class=\"supplement\">例） タグ タロウ</span></td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<th><label for=\"mail\">メールアドレス</label></th>\r\n");
            out.write("<td></td>\r\n");
            out.write("<td>");
            if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write(" <span class=\"supplement\">（半角英数字）</span><br>\r\n");
            out.write("<span class=\"supplement\">ご入力間違いのないようにご注意ください</span>\r\n");
            out.write("\r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<!--\r\n");
            out.write("<tr>\r\n");
            out.write("<th><label for=\"tel1\">電話番号</label></th>\r\n");
            out.write("<td class=\"arbitrary\"></td>\r\n");
            out.write("<td><input type=\"text\" name=\"tel1\" id=\"tel1\" size=\"12\"> - <input type=\"text\" name=\"tel2\" id=\"tel2\" size=\"12\"> - <input type=\"text\" name=\"tel3\" id=\"tel3\" size=\"12\"> <span class=\"supplement\">（半角数字）</span></td>\r\n");
            out.write("</tr>\r\n");
            out.write("-->\r\n");
            out.write("<tr>\r\n");
            out.write("<th rowspan=\"3\"><label>ご住所</label></th>\r\n");
            out.write("<td class=\"arbitrary\">\r\n");
            out.write("<!-- <input type=\"submit\" value=\"入力内容の確認画面\" style=\"position: absolute; left: 600px;\" class=\"button2\" formaction=\"http://localhost:8080/Izumi/confirmation\">-->\r\n");
            out.write("<button class=\"button2\" type=\"submit\" style=\"position: absolute; left: 600px;\" onClick=\"button()\" >入力内容の確認画面へ</button>\r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("<tr>\r\n");
            out.write("<td></td>\r\n");
            out.write("\r\n");
            out.write("<!--都道府県の選択-->\r\n");
            out.write("\r\n");
            out.write("<!-- <td><select name=\"prefecture\" id=\"prefecture\">  -->\r\n");
            out.write("\r\n");
            out.write("<td>\r\n");
            if (_jspx_meth_form_005fselect_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<!--都道府県以下の住所入力-->\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"arbitrary\"></td>\r\n");
            out.write("<td>");
            if (_jspx_meth_form_005finput_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("<br>\r\n");
            out.write("<span class=\"supplement\">例） 千代田区大手町1-2-3 ○○ビル10F</span></td>\r\n");
            out.write("</tr>\r\n");
            out.write("</tbody>\r\n");
            out.write("</table>\r\n");
            out.write("<!--<button class=\"button2\" type=\"submit\" style=\"position: absolute; right: 10px; top: 360px\">入力内容の確認画面へ</button>\r\n");
            out.write(" <div id=\"button2\">\r\n");
            out.write("  <input type=\"submit\" class=\"button2\" name=\"button\" value=\"入力内容の確認\" >\r\n");
            out.write("</div> -->\r\n");
            out.write("\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
        _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fid.reuse(_jspx_th_form_005fform_005f0);
      }
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function button(){\r\n");
      out.write("  str1=document.forms.form.member.value;\r\n");
      out.write("  str2=document.forms.form.name1.value;\r\n");
      out.write("  str3=document.forms.form.name2.value;\r\n");
      out.write("  str4=document.forms.form.mail.value;\r\n");
      out.write("  str5=document.forms.form.prefecture.value;\r\n");
      out.write("  str6=document.forms.form.address.value;\r\n");
      out.write("\r\n");
      out.write("  str1=str1.replace(/[^1-9]/,\"\");\r\n");
      out.write("  str2=str2.replace(/[^一-龠々ぁ-んァ-ヶ 　]/,\"\");\r\n");
      out.write("  str3=str3.replace(/[^ァ-ヶ 　]/,\"\");\r\n");
      out.write("  str4=str4.replace(/[^a-zA-Z0-9@._-]+/,\"\");\r\n");
      out.write("  str6=str6.replace(/[^一-龠々ぁ-んァ-ヶa-zA-Z0-9０-９-]+/,\"\");\r\n");
      out.write("  str6=str6.replace(/(北海道)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(青森)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(岩手)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(宮城)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(秋田)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(山形)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(福島)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(東京)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(神奈川)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(埼玉)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(千葉)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(茨城)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(栃木)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(群馬)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(山梨)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(新潟)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(長野)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(富山)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(石川)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(福井)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(愛知)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(岐阜)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(静岡)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(三重)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(大阪)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(兵庫)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(京都)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(滋賀)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(奈良)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(和歌山)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(鳥取)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(島根)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(岡山)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(広島)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(山口)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(徳島)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(香川)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(愛媛)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(高知)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(福岡)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(佐賀)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(長崎)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(熊本)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(大分)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(宮崎)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(鹿児島)/,\"\");\r\n");
      out.write("  str6=str6.replace(/(沖縄)/,\"\");\r\n");
      out.write("\r\n");
      out.write("  if((str1!=\"\")&&(str2!=\"\")&&(str3!=\"\")&&(str4!=\"\")){\r\n");
      out.write("\tif((str5==\"その他\")||((str5!=\"\")&&(str6!=\"\"))){\r\n");
      out.write("      document.form.action = '/Izumi/confirmation';\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("          <p id=\"copyright\">Copyright &copy;<a href=\"http://hotelizumi.com\">hotelizumi</a> All Rights Reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/form.jsp(82,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("input1");
    // /WEB-INF/views/form.jsp(82,13) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "name", "member");
    // /WEB-INF/views/form.jsp(82,13) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setId("member");
    // /WEB-INF/views/form.jsp(82,13) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setSize("5");
    // /WEB-INF/views/form.jsp(82,13) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setAutocomplete("off");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/form.jsp(89,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setPath("input2");
    // /WEB-INF/views/form.jsp(89,13) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "name", "name1");
    // /WEB-INF/views/form.jsp(89,13) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setId("name1");
    // /WEB-INF/views/form.jsp(89,13) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setSize("50");
    // /WEB-INF/views/form.jsp(89,13) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setAutocomplete("off");
    // /WEB-INF/views/form.jsp(89,13) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setMaxlength("15");
    int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
      if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/form.jsp(96,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setPath("input3");
    // /WEB-INF/views/form.jsp(96,4) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "name", "name2");
    // /WEB-INF/views/form.jsp(96,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setId("name2");
    // /WEB-INF/views/form.jsp(96,4) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setSize("50");
    // /WEB-INF/views/form.jsp(96,4) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setAutocomplete("off");
    // /WEB-INF/views/form.jsp(96,4) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setMaxlength("15");
    int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
      if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f2.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/form.jsp(103,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setPath("input4");
    // /WEB-INF/views/form.jsp(103,4) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "name", "mail");
    // /WEB-INF/views/form.jsp(103,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setId("mail");
    // /WEB-INF/views/form.jsp(103,4) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setSize("50");
    // /WEB-INF/views/form.jsp(103,4) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setAutocomplete("off");
    int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
      if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f3.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fsize_005fpath_005fname_005fid_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_form_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fname_005fid.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    _jspx_th_form_005fselect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/form.jsp(131,0) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fselect_005f0.setPath("input5");
    // /WEB-INF/views/form.jsp(131,0) null
    _jspx_th_form_005fselect_005f0.setDynamicAttribute(null, "name", "prefecture");
    // /WEB-INF/views/form.jsp(131,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fselect_005f0.setId("prefecture");
    int[] _jspx_push_body_count_form_005fselect_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fselect_005f0 = _jspx_th_form_005fselect_005f0.doStartTag();
      if (_jspx_eval_form_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("<option value=\"\">都道府県の選択</option>\r\n");
          out.write("<option value=\"北海道\">北海道</option>\r\n");
          out.write("<option value=\"青森県\">青森県</option>\r\n");
          out.write("<option value=\"岩手県\">岩手県</option>\r\n");
          out.write("<option value=\"宮城県\">宮城県</option>\r\n");
          out.write("<option value=\"秋田県\">秋田県</option>\r\n");
          out.write("<option value=\"山形県\">山形県</option>\r\n");
          out.write("<option value=\"福島県\">福島県</option>\r\n");
          out.write("<option value=\"東京都\">東京都</option>\r\n");
          out.write("<option value=\"神奈川県\">神奈川県</option>\r\n");
          out.write("<option value=\"埼玉県\">埼玉県</option>\r\n");
          out.write("<option value=\"千葉県\">千葉県</option>\r\n");
          out.write("<option value=\"茨城県\">茨城県</option>\r\n");
          out.write("<option value=\"栃木県\">栃木県</option>\r\n");
          out.write("<option value=\"群馬県\">群馬県</option>\r\n");
          out.write("<option value=\"山梨県\">山梨県</option>\r\n");
          out.write("<option value=\"新潟県\">新潟県</option>\r\n");
          out.write("<option value=\"長野県\">長野県</option>\r\n");
          out.write("<option value=\"富山県\">富山県</option>\r\n");
          out.write("<option value=\"石川県\">石川県</option>\r\n");
          out.write("<option value=\"福井県\">福井県</option>\r\n");
          out.write("<option value=\"愛知県\">愛知県</option>\r\n");
          out.write("<option value=\"岐阜県\">岐阜県</option>\r\n");
          out.write("<option value=\"静岡県\">静岡県</option>\r\n");
          out.write("<option value=\"三重県\">三重県</option>\r\n");
          out.write("<option value=\"大阪府\">大阪府</option>\r\n");
          out.write("<option value=\"兵庫県\">兵庫県</option>\r\n");
          out.write("<option value=\"京都府\">京都府</option>\r\n");
          out.write("<option value=\"滋賀県\">滋賀県</option>\r\n");
          out.write("<option value=\"奈良県\">奈良県</option>\r\n");
          out.write("<option value=\"和歌山県\">和歌山県</option>\r\n");
          out.write("<option value=\"鳥取県\">鳥取県</option>\r\n");
          out.write("<option value=\"島根県\">島根県</option>\r\n");
          out.write("<option value=\"岡山県\">岡山県</option>\r\n");
          out.write("<option value=\"広島県\">広島県</option>\r\n");
          out.write("<option value=\"山口県\">山口県</option>\r\n");
          out.write("<option value=\"徳島県\">徳島県</option>\r\n");
          out.write("<option value=\"香川県\">香川県</option>\r\n");
          out.write("<option value=\"愛媛県\">愛媛県</option>\r\n");
          out.write("<option value=\"高知県\">高知県</option>\r\n");
          out.write("<option value=\"福岡県\">福岡県</option>\r\n");
          out.write("<option value=\"佐賀県\">佐賀県</option>\r\n");
          out.write("<option value=\"長崎県\">長崎県</option>\r\n");
          out.write("<option value=\"熊本県\">熊本県</option>\r\n");
          out.write("<option value=\"大分県\">大分県</option>\r\n");
          out.write("<option value=\"宮崎県\">宮崎県</option>\r\n");
          out.write("<option value=\"鹿児島県\">鹿児島県</option>\r\n");
          out.write("<option value=\"沖縄県\">沖縄県</option>\r\n");
          out.write("<option value=\"その他\">その他</option>\r\n");
          out.write("<!-- </select> -->\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_form_005fselect_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fselect_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fselect_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fselect_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fname_005fid.reuse(_jspx_th_form_005fselect_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f4.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/form.jsp(190,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setPath("input6");
    // /WEB-INF/views/form.jsp(190,4) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "name", "address");
    // /WEB-INF/views/form.jsp(190,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setId("address");
    // /WEB-INF/views/form.jsp(190,4) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "value", " ");
    // /WEB-INF/views/form.jsp(190,4) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setSize("50");
    // /WEB-INF/views/form.jsp(190,4) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setAutocomplete("off");
    // /WEB-INF/views/form.jsp(190,4) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setMaxlength("40");
    int[] _jspx_push_body_count_form_005finput_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f4 = _jspx_th_form_005finput_005f4.doStartTag();
      if (_jspx_th_form_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f4.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fsize_005fpath_005fname_005fmaxlength_005fid_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f4);
    }
    return false;
  }
}
